//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemaABD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EchipeStudent
    {
        public int IdEchipeStudent { get; set; }
        public Nullable<int> IDStudent { get; set; }
        public Nullable<int> IdEchipe { get; set; }
    
        public virtual Echipe Echipe { get; set; }
        public virtual Studenti Studenti { get; set; }
    }
}
