//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemaABD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportsEntities5 : DbContext
    {
        public SportsEntities5()
            : base("name=SportsEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Utilizatori> Utilizatoris { get; set; }
        public virtual DbSet<Sporturi> Sporturis { get; set; }
        public virtual DbSet<SporturiStudent> SporturiStudents { get; set; }
        public virtual DbSet<Studenti> Studentis { get; set; }
        public virtual DbSet<Antrenori> Antrenoris { get; set; }
        public virtual DbSet<Echipe> Echipes { get; set; }
        public virtual DbSet<EchipeStudent> EchipeStudents { get; set; }
        public virtual DbSet<EvenimentSportivEchipe> EvenimentSportivEchipes { get; set; }
        public virtual DbSet<EvenimentSportivIndividual> EvenimentSportivIndividuals { get; set; }
    }
}
