//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemaABD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvenimentSportivIndividual
    {
        public int IdEvenimentSportivIndividual { get; set; }
        public Nullable<int> player1 { get; set; }
        public Nullable<int> player2 { get; set; }
        public Nullable<int> scor1 { get; set; }
        public Nullable<int> scor2 { get; set; }
        public string nume { get; set; }
        public string stare { get; set; }
    
        public virtual Studenti Studenti { get; set; }
        public virtual Studenti Studenti1 { get; set; }
    }
}
