//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemaABD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvenimentSportivEchipe
    {
        public int IdEvenimentSportivEchipe { get; set; }
        public Nullable<int> echipa1 { get; set; }
        public Nullable<int> echipa2 { get; set; }
        public Nullable<int> scor1 { get; set; }
        public Nullable<int> scor2 { get; set; }
        public string nume { get; set; }
        public string stare { get; set; }
    
        public virtual Echipe Echipe { get; set; }
        public virtual Echipe Echipe1 { get; set; }
    }
}
