//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemaABD
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Utilizatori
    {
        public int IDUtilizator { get; set; }
        public string username { get; set; }
        public string parola { get; set; }
    }
}
